name: mektep_rings
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  intl: ^0.20.2
  just_audio: ^0.10.2
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/audio/default_lesson.mp3
    - assets/audio/first_lesson.mp3
    - assets/audio/second_lesson.mp3
    - assets/audio/third_lesson.mp3
    - assets/audio/fourth_lesson.mp3
    - assets/audio/fifth_lesson.mp3
    - assets/audio/sixth_lesson.mp3
    - assets/audio/exit_lesson.mp3
    - assets/audio/exit_last_lesson.mp3

